[IV-21-22] Objetivo 2
ismaelmontesinos/PracticaIV pull request #21
Opened 2021-11-14 19:55 UTC by agr8

- Se ha organizado el repositorio siguiendo las buenas prácticas de python, creando para ello el directorio '_**inmuventa**_'.

- Se ha creado la estructura de datos que representa un inmueble en el fichero '**_inmueble.py_**'

Esto avanza la implementación del primer Milestone y cierra los issues #18 y #20 .

2021-11-15 18:25 UTC, agr8 commented
Ya han pasado correctamente los tests. @ismaelmontesinos, revisa el PR cuando puedas por si tengo que modificar algo para cumplir con el objetivo. :pray:

2021-11-18 08:24 UTC, JJ requested changes
Aparte de los comentarios en línea, mira las buenas prácticas en mensajes de commit.

2021-11-18 08:24 UTC, JJ commented on inmuventa/inmueble.py
> +        self.numero_puerta = numero_puerta
¿Todo esto influye en la lógica de negocio? Si es simplemente pare identificar al inmueble, en un PMV no hace falta.

2021-11-18 08:24 UTC, JJ commented on inmuventa/inmueble.py
> +class Inmueble:
Si no va a variar, por favor considera usar "Frozen"

2021-11-18 11:07 UTC, agr8 commented
@JJ, cambios realizados también en la clase Localizacion. He eliminado todos los atributos opcionales y he utilizado _(frozen=True)_ para hacer inmutables ambas clases. También he intentado seguir las buenas prácticas en los nuevos commits. De ahora en adelante, tendré más cuidado para cumplir con las buenas prácticas :sweat_smile:

2021-11-19 06:44 UTC, JJ approved these changes
Se han intentado seguir las buenas prácticas, pero rara vez un commit cerrará dos issues. Puedes referirte a un PR tal como este si estás tratando de resolver lo que se comenta en una revisión.
Rogaría a @ismaelmontesinos que fuera un poco más diligente revisando y haciendo sugerencias. Una vez que ya lo haya aprobado yo, @agr8 no tiene por qué hacer ningún cambio más y tendrás que usar lo que haya para tu siguiente objetivo.

2021-11-19 12:20 UTC, ismaelmontesinos commented
Por mi parte está todo perfecto tal y como hemos comentado tanto en el issue (#18) como por telegram y en presencial, por lo tanto por mi parte estaría listo para el merge.

2021-11-21 08:44 UTC, JJ approved these changes
No es buena práctica cerrar dos issues con el mismo commit, por lo demás correcto.

2021-11-21 18:08 UTC, agr8 commented
Lo tengo en cuenta para los siguientes objetivos, gracias :smile:

2021-11-21 18:23 UTC, merged